version: "3.3"

services:
  neo4j:
    container_name: kb-neo4j
    image: neo4j:5.12.0
    environment:
      - NEO4J_AUTH=neo4j/smartbsmartb
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    ports:
      - 7687:7687
      - 7474:7474  # browser interface (localhost:7474)
    volumes:
      - ./infra/data/neo4j:/data
