
INDEX_EMBEDDED = "embeddedIndex"
LABEL_EMBEDDED = "Embedded"
INDEX_EMBEDDED_NODE = "embeddedNodeIndex"
LABEL_EMBEDDED_NODE = "EmbeddedNode"
PROPERTY_EMBED_TEXT = "embedText"
PROPERTY_EMBED_VECTOR = "embedVector"

LABEL_REQUIREMENT = "Requirement"
LABEL_INFORMATION_CONCEPT = "InformationConcept"
LABEL_DATA_UNIT = "DataUnit"
LABEL_DOCUMENT = "Document"
LABEL_DOCUMENT_CHUNK = "DocumentChunk"

EMBEDDABLE_NODE_LABELS = [LABEL_REQUIREMENT, LABEL_INFORMATION_CONCEPT, LABEL_DATA_UNIT, LABEL_DOCUMENT, LABEL_DOCUMENT_CHUNK]
EMBEDDABLE_LABELS = EMBEDDABLE_NODE_LABELS + [LABEL_DOCUMENT_CHUNK]
